### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by mrcat323** [mrcat323/team-fight-tactics#10]
https://github.com/mrcat323/team-fight-tactics/blob/c2bd9e66e0bd9a891c2e80dda72536d508c0f052/routes/api.php#L30C23-L30C23

Change `/product/search` to `/search`

**Comment by wascrashed** [comment]
> https://github.com/mrcat323/team-fight-tactics/blob/c2bd9e66e0bd9a891c2e80dda72536d508c0f052/routes/api.php#L30C23-L30C23
> 
> Change `/product/search` to `/search`

Fixed
